### ISSUE TITLE
Option to show output even if the tasks succeed

### ISSUE THREAD

**Issue by pragatheeswarans** [theenadayalank/lint-prepush#134]
Is there an option to show the output of the tasks even if they succeed? 

Like a `--verbose` flag. 

Currently the output is displayed only when there is an error. I can set the lint rule as `warn` to show warning when it is executed. This warning is not displayed in the terminal.

**Comment by theenadayalank** [comment]
Hi @pragatheeswarans  ! Thank you for raising this issue.

So far, `lint-prepush` will not display the sub-tasks list unless or until any of the sub-tasks get failed (throws an error).

A configurable option can be provided to support this feature. Would you mind opening a PR for this case?

**Comment by pragatheeswarans** [comment]
Sure @theenadayalank Here is the [PR](https://github.com/theenadayalank/lint-prepush/pull/135)

**Comment by pragatheeswarans** [comment]
@theenadayalank Did you get a chance to review the PR?

**Comment by theenadayalank** [comment]
Implemented here https://github.com/theenadayalank/lint-prepush/pull/135.

Thank you @pragatheeswarans 😃
