### ISSUE TITLE
lint-prepush RUNS for all commits when I rebase my BRANCH against MASTER

### ISSUE THREAD

**Issue by RakChamp25** [theenadayalank/lint-prepush#71]
In Version 1.0 : lint-prepush runs for all the previous commits, when i rebase my current branch against base/master branch.

**Comment by theenadayalank** [comment]
There was an issue with `v1.0.0`. It's been fixed in `v1.1.0`. Update the `lint-prepush` version to `v1.1.0` in your application.

Fixed: #70
